//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP123_Sharp_Mail_Order.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COMP123_Sharp_Mail_Order.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Button.
        /// </summary>
        internal static string CalculateButtonE {
            get {
                return ResourceManager.GetString("CalculateButtonE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculer Bouton.
        /// </summary>
        internal static string CalculateButtonF {
            get {
                return ResourceManager.GetString("CalculateButtonF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Button.
        /// </summary>
        internal static string ClearButtonE {
            get {
                return ResourceManager.GetString("ClearButtonE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacement.
        /// </summary>
        internal static string ClearButtonF {
            get {
                return ResourceManager.GetString("ClearButtonF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string EmployeeIDLabelE {
            get {
                return ResourceManager.GetString("EmployeeIDLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employé ID.
        /// </summary>
        internal static string EmployeeIDLabelF {
            get {
                return ResourceManager.GetString("EmployeeIDLabelF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string EmployeeNameLabelE {
            get {
                return ResourceManager.GetString("EmployeeNameLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;employé.
        /// </summary>
        internal static string EmployeeNameLabelF {
            get {
                return ResourceManager.GetString("EmployeeNameLabelF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishRadioButtonE {
            get {
                return ResourceManager.GetString("EnglishRadioButtonE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglais.
        /// </summary>
        internal static string EnglishRadioButtonF {
            get {
                return ResourceManager.GetString("EnglishRadioButtonF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string FrenchRadioButtonE {
            get {
                return ResourceManager.GetString("FrenchRadioButtonE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string FrenchRadioButtonF {
            get {
                return ResourceManager.GetString("FrenchRadioButtonF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graphIcon {
            get {
                object obj = ResourceManager.GetObject("graphIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Worked.
        /// </summary>
        internal static string HoursWorkedLabelE {
            get {
                return ResourceManager.GetString("HoursWorkedLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heures Travaillées.
        /// </summary>
        internal static string HoursWorkedLabelF {
            get {
                return ResourceManager.GetString("HoursWorkedLabelF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string LanguagesGroupBoxE {
            get {
                return ResourceManager.GetString("LanguagesGroupBoxE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langues.
        /// </summary>
        internal static string LanguagesGroupBoxF {
            get {
                return ResourceManager.GetString("LanguagesGroupBoxF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string PrintButtonE {
            get {
                return ResourceManager.GetString("PrintButtonE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        internal static string PrintButtonF {
            get {
                return ResourceManager.GetString("PrintButtonF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sale_big {
            get {
                object obj = ResourceManager.GetObject("sale_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Bonus.
        /// </summary>
        internal static string SalesBonusFormE {
            get {
                return ResourceManager.GetString("SalesBonusFormE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boni de vente.
        /// </summary>
        internal static string SalesBonusFormF {
            get {
                return ResourceManager.GetString("SalesBonusFormF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Bonus.
        /// </summary>
        internal static string SalesBonusLabelE {
            get {
                return ResourceManager.GetString("SalesBonusLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus de vente.
        /// </summary>
        internal static string SalesBonusLabelF {
            get {
                return ResourceManager.GetString("SalesBonusLabelF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        internal static string TotalSalesLabelE {
            get {
                return ResourceManager.GetString("TotalSalesLabelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total des ventes.
        /// </summary>
        internal static string TotalSalesLabelF {
            get {
                return ResourceManager.GetString("TotalSalesLabelF", resourceCulture);
            }
        }
    }
}
